In [21]:
import pandas as pd
import scipy.sparse as sparse
import numpy as np
from scipy.sparse.linalg import spsolve

In [23]:
main_path = "D:\Grad Notes\Search\Project\Data\yelp_dataset\dataset\\"

In [24]:
##Get user and business data
df_rev = pd.read_csv(main_path+"review.csv")
print(df_rev.shape)

df_bus = pd.read_csv(main_path+"business.csv")
print(df_bus.shape)

(4736897, 9)
   funny                 user_id               review_id  \
0      0  cjpdDjZyprfyDG3RlkVG3w  VfBHSwC5Vz_pbFluy07i9Q
1      0  bjTcT8Ty4cJZhEOEo01FGA  3zRpneRKDsOPq92tq7ybAA
2      0  AXgRULmWcME7J6Ix3I--ww  ne5WhI1jUFOcRn-b-gAzHA
3      0  oU2SSOmsp_A8JYI7Z2JJ5w  llmdwOgDReucVoWEry61Lw
4      0  0xtbPEna2Kei11vsU-U2Mw  DuffS87NaSMDmIfluvT83g

                                                text             business_id  \
0  My girlfriend and I stayed here for 3 nights a...  uYHaNptLzDLoV_JZ_MuzUA
1  If you need an inexpensive place to stay for a...  uYHaNptLzDLoV_JZ_MuzUA
2  Mittlerweile gibt es in Edinburgh zwei Ableger...  uYHaNptLzDLoV_JZ_MuzUA
3  Location is everything and this hotel has it! ...  uYHaNptLzDLoV_JZ_MuzUA
4  gute lage im stadtzentrum. shoppingmeile und s...  uYHaNptLzDLoV_JZ_MuzUA

   stars        date  useful  cool
0      5  2016-07-12       0     0
1      3  2016-10-02       0     0
2      3  2015-09-17       0     0
3      4  2016-08-21       0     0
4      5  2013-11-20       0     0
(156639, 101)
  attributes.Ambience.divey attributes.RestaurantsDelivery  \
0                       NaN                            NaN
1                     False                           True
2                       NaN                            NaN
3                       NaN                            NaN
4                     False                          False

  attributes.DogsAllowed postal_code hours.Thursday  \
0                    NaN       44143    10:00-21:00
1                    NaN       28215    10:00-22:00
2                    NaN     M4K 1N7    10:00-19:00
3                    NaN       85258     9:00-17:00
4                    NaN       85016            NaN

  attributes.HairSpecializesIn.coloring attributes.BestNights.sunday  \
0                                   NaN                          NaN
1                                   NaN                          NaN
2                                   NaN                          NaN
3                                   NaN                          NaN
4                                   NaN                          NaN

  attributes.BYOB attributes.AgesAllowed attributes.Music.video  \
0             NaN                    NaN                    NaN
1             NaN                    NaN                    NaN
2             NaN                    NaN                    NaN
3             NaN                    NaN                    NaN
4             NaN                    NaN                    NaN

             ...            attributes.Caters  \
0            ...                          NaN
1            ...                          NaN
2            ...                          NaN
3            ...                          NaN
4            ...                         True

   attributes.RestaurantsReservations  \
0                                 NaN
1                               False
2                                 NaN
3                                 NaN
4                               False

  attributes.DietaryRestrictions.dairy-free  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN

  attributes.DietaryRestrictions.vegan attributes.Ambience.romantic  \
0                                  NaN                          NaN
1                                  NaN                        False
2                                  NaN                          NaN
3                                  NaN                          NaN
4                                  NaN                        False

  attributes.Music.jukebox attributes.Ambience.upscale  \
0                      NaN                         NaN
1                      NaN                       False
2                      NaN                         NaN
3                      NaN                         NaN
4                      NaN                       False

  attributes.RestaurantsTakeOut attributes.BikeParking  \
0                           NaN                   True
1                          True                    NaN
2                           NaN                   True
3                           NaN                    NaN
4                          True                   True

  attributes.OutdoorSeating
0                       NaN
1                     False
2                     False
3                       NaN
4                     False

[5 rows x 101 columns]

In [25]:
df_rev.head()

,funny,user_id,review_id,text,business_id,stars,date,useful,cool
0,0,cjpdDjZyprfyDG3RlkVG3w,VfBHSwC5Vz_pbFluy07i9Q,My girlfriend and I stayed here for 3 nights a...,uYHaNptLzDLoV_JZ_MuzUA,5,2016-07-12,0,0
1,0,bjTcT8Ty4cJZhEOEo01FGA,3zRpneRKDsOPq92tq7ybAA,If you need an inexpensive place to stay for a...,uYHaNptLzDLoV_JZ_MuzUA,3,2016-10-02,0,0
2,0,AXgRULmWcME7J6Ix3I--ww,ne5WhI1jUFOcRn-b-gAzHA,Mittlerweile gibt es in Edinburgh zwei Ableger...,uYHaNptLzDLoV_JZ_MuzUA,3,2015-09-17,0,0
3,0,oU2SSOmsp_A8JYI7Z2JJ5w,llmdwOgDReucVoWEry61Lw,Location is everything and this hotel has it! ...,uYHaNptLzDLoV_JZ_MuzUA,4,2016-08-21,0,0
4,0,0xtbPEna2Kei11vsU-U2Mw,DuffS87NaSMDmIfluvT83g,gute lage im stadtzentrum. shoppingmeile und s...,uYHaNptLzDLoV_JZ_MuzUA,5,2013-11-20,0,0

In [46]:
df_sub = df_rev[['user_id','business_id','stars']].groupby(['user_id','business_id']).agg('mean').reset_index()
df_sub.head()
# df_sub1 = df_sub.drop_duplicates()

# float(df_sub1.shape[0])/df_sub.shape[0]

                  user_id             business_id  stars
0  ---1lKK3aKOuomHnwAkAow  --9e1ONYQuAa-CB_Rrw7Tw      4
1  ---1lKK3aKOuomHnwAkAow  -ErwgUmZ1-jHW_rSu55jlg      5
2  ---1lKK3aKOuomHnwAkAow  0YhT9HCBkU394IG6tQVtNQ      1
3  ---1lKK3aKOuomHnwAkAow  1JgaRBX0oiRsvEhHF3ZMjw      1
4  ---1lKK3aKOuomHnwAkAow  1Vn_lex3LGGwuTo-xeJnww      5

In [52]:
##Get businesses with atleast 20 reviews
df_get = df_rev[['business_id','review_id']]
df_get.drop_duplicates(inplace=True)

df_counts = pd.DataFrame(df_rev['business_id'].value_counts())
df_counts.reset_index(inplace=True)
df_counts.head()

df_min = df_counts[df_counts['business_id'] > 19]
bus_id_list = df_min['index'].tolist()
len(bus_id_list)

df_rev_new = df_rev[df_rev['business_id'].isin(bus_id_list)]
df_rev_new.shape

(3916402, 9)

In [54]:
df_rev_new.head()

,funny,user_id,review_id,text,business_id,stars,date,useful,cool
16,0,kzyLOqiJvyw_FWFTw2rjiQ,ByRzJ8rF2KJWLr-cUNU6EA,"This place is horrible, we were so excited to ...",jQsNFOzDpxPmOurSWCg1vQ,1,2017-06-03,0,0
17,0,WZXp9-V2dqRRJqhGgRqueA,i5UwUPlQFPLcE8p2gPFwBw,"For being fairly ""fast"" food.. Pei Wei (pronou...",jQsNFOzDpxPmOurSWCg1vQ,4,2015-03-26,1,0
18,1,XylT12exfdLiI_3uDLVIpw,EyQyvTTg2jX4or9bB8PC9g,"I decided to try it out, I'm celiac and theref...",jQsNFOzDpxPmOurSWCg1vQ,5,2012-12-30,2,1
19,1,Ji9PeffxjwqPLO7pEfSpKQ,G-EFA005besj5uHsH0sQFA,I'm not saying Pei Wei is the best asian food ...,jQsNFOzDpxPmOurSWCg1vQ,3,2009-01-12,1,1
20,0,TLIWzAJPrET0zX4_vgvLhg,6PcJSGUBSLjt4VLXos5C4A,Sometimes the food is spot on and delicious an...,jQsNFOzDpxPmOurSWCg1vQ,3,2015-07-11,0,0

In [66]:
#Get list of reviews
df_rev_sub = df_rev_new.sample(frac = 0.001)

In [69]:
rp = df_rev_sub.pivot_table(values='stars', index='user_id', columns='business_id', fill_value=0)
rp.head()

business_id,--6MefnULPED_I942VcFNA,--qJNlGWyvPJfBrqwp9c0w,--ujyvoQlwVoBgMYtADiLA,-0NhdsDJsdarxyDPR523ZQ,-1VaIJza42Hjev6ukacCNg,-1xuC540Nycht_iWFeJ-dw,-2ToCaDFpTNmmg3QFzxcWg,-3oxnPPPU3YoxO9M1I2idg,-4TMQnQJW1yd6NqGRDvAeA,-6h3K1hj0d4DRcZNUtHDuw,...,zpoZ6WyQUYff18-z4ZU1mA,zrcs31Gt6HuWX_RCWW-mCQ,zsQk990PubOHjr1YcLkQFw,zswdqM8Av3KxVv9o7_6ORA,ztxAbArApdQIhMoPF_ttiA,zu1JllEH2cjH6uijHIB6TQ,zuVvDYJkKAbXQTTBauAqJQ,zw4Legbcu018p5WcZ74iWA,zw9_mqWBn1QCfZg88w0Exg,zzSYBWuv_fXGtSgsO-6_1g
user_id,,,,,,,,,,,,,,,,,,,,,
--Qh8yKWAvIP4V4K8ZPfHA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-3gUn9YImya8KvHKeHMmFQ,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-4-psQpwbDvu_BPCvD3JHQ,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-4GTxkV3NWPp7mmoO-eR0A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
-4beu8_A2fVZLmAjj2Qlsg,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [71]:
R = rp.as_matrix()
user_ratings_mean = np.mean(R, axis = 1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)

In [72]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(R_demeaned, k = 50)

In [74]:
sigma = np.diag(sigma)

In [76]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = rp.columns)

In [80]:
def recommend_movies(predictions_df, userID, bus_df, original_ratings_df, num_recommendations=5):
    
    # Get and sort the user's predictions
    user_row_number = userID - 1 # UserID starts at 1, not 0
    sorted_user_predictions = predictions_df.iloc[user_row_number].sort_values(ascending=False)
    
    # Get the user's data and merge in the movie information.
    user_data = original_ratings_df[original_ratings_df.user_id == '-4GTxkV3NWPp7mmoO-eR0A']
    print("here",user_data.shape)
    user_full = (user_data.merge(bus_df, how = 'left', left_on = 'business_id', right_on = 'business_id')
                 )

    print 'User {0} has already rated {1} businesses.'.format(userID, user_full.shape[0])
    print 'Recommending the highest {0} predicted ratings businesses not already rated.'.format(num_recommendations)
    
    # Recommend the highest predicted rating movies that the user hasn't seen yet.
    recommendations = (bus_df[~bus_df['business_id'].isin(user_full['business_id'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'business_id',
               right_on = 'business_id').
         rename(columns = {user_row_number: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )

    return user_full, recommendations

already_rated, predictions = recommend_movies(preds_df, 4, df_bus, df_rev_new, 10)

('here', (1, 9))
User 4 has already rated 1 movies.
Recommending the highest 10 predicted ratings movies not already rated.
Here    funny                 user_id               review_id  \
0      0  -4GTxkV3NWPp7mmoO-eR0A  T6n921F33DewN4EXZxseBw

                                                text             business_id  \
0  nope  over rated-- pretty restaurant  but it s...  azIZRqX_1qbp0_6GKSgSAA

   stars_x        date  useful  cool attributes.Ambience.divey  \
0        1  2013-08-02       0     0                     False

             ...            attributes.Caters  \
0            ...                        False

  attributes.RestaurantsReservations  \
0                               True

  attributes.DietaryRestrictions.dairy-free  \
0                                       NaN

  attributes.DietaryRestrictions.vegan attributes.Ambience.romantic  \
0                                  NaN                        False

  attributes.Music.jukebox attributes.Ambience.upscale  \
0                      NaN                        True

  attributes.RestaurantsTakeOut attributes.BikeParking  \
0                         False                  False

  attributes.OutdoorSeating
0                     False

[1 rows x 109 columns]        attributes.Ambience.divey attributes.RestaurantsDelivery  \
139877                     False                          False
10896                      False                            NaN
38887                      False                          False
84520                        NaN                            NaN
32515                      False                          False
20815                      False                          False
86971                      False                          False
146643                     False                          False
134679                       NaN                            NaN
58663                      False                          False

       attributes.DogsAllowed postal_code hours.Thursday  \
139877                  False       89169     11:30-1:00
10896                     NaN       89109     22:30-4:00
38887                   False       28205      0:00-0:00
84520                     NaN       89109    10:00-22:00
32515                    True       89123     9:00-15:00
20815                     NaN       89109     6:00-23:00
86971                     NaN       89147      0:00-0:00
146643                    NaN       89145    11:00-23:00
134679                    NaN       89109      0:00-0:00
58663                     NaN       85018    11:00-22:00

       attributes.HairSpecializesIn.coloring attributes.BestNights.sunday  \
139877                                   NaN                          NaN
10896                                    NaN                         True
38887                                    NaN                          NaN
84520                                    NaN                          NaN
32515                                    NaN                          NaN
20815                                    NaN                          NaN
86971                                    NaN                        False
146643                                   NaN                          NaN
134679                                   NaN                          NaN
58663                                    NaN                          NaN

       attributes.BYOB attributes.AgesAllowed attributes.Music.video  \
139877             NaN                    NaN                    NaN
10896              NaN                 21plus                  False
38887              NaN                    NaN                    NaN
84520              NaN                    NaN                    NaN
32515              NaN                    NaN                    NaN
20815              NaN                    NaN                    NaN
86971            False                    NaN                  False
146643             NaN                    NaN                    NaN
134679             NaN                    NaN                    NaN
58663              NaN                    NaN                    NaN

                  ...            attributes.Caters  \
139877            ...                         True
10896             ...                          NaN
38887             ...                         True
84520             ...                          NaN
32515             ...                         True
20815             ...                        False
86971             ...                         True
146643            ...                         True
134679            ...                          NaN
58663             ...                        False

        attributes.RestaurantsReservations  \
139877                                True
10896                                 True
38887                                False
84520                                  NaN
32515                                False
20815                                False
86971                                False
146643                                True
134679                                 NaN
58663                                 True

       attributes.DietaryRestrictions.dairy-free  \
139877                                       NaN
10896                                        NaN
38887                                        NaN
84520                                        NaN
32515                                        NaN
20815                                        NaN
86971                                        NaN
146643                                       NaN
134679                                       NaN
58663                                        NaN

       attributes.DietaryRestrictions.vegan attributes.Ambience.romantic  \
139877                                  NaN                        False
10896                                   NaN                        False
38887                                   NaN                        False
84520                                   NaN                          NaN
32515                                   NaN                        False
20815                                   NaN                        False
86971                                   NaN                        False
146643                                  NaN                        False
134679                                  NaN                          NaN
58663                                   NaN                        False

       attributes.Music.jukebox attributes.Ambience.upscale  \
139877                      NaN                       False
10896                     False                       False
38887                       NaN                       False
84520                       NaN                         NaN
32515                       NaN                       False
20815                       NaN                       False
86971                      True                       False
146643                      NaN                       False
134679                      NaN                         NaN
58663                       NaN                       False

       attributes.RestaurantsTakeOut attributes.BikeParking  \
139877                          True                   True
10896                            NaN                  False
38887                           True                   True
84520                            NaN                    NaN
32515                           True                   True
20815                           True                  False
86971                           True                   True
146643                          True                   True
134679                           NaN                    NaN
58663                           True                   True

       attributes.OutdoorSeating
139877                      True
10896                      False
38887                       True
84520                        NaN
32515                       True
20815                      False
86971                      False
146643                      True
134679                       NaN
58663                       True

[10 rows x 101 columns]

1183362

156638